---

loadtarget:
  host: http://localhost:8080

server:
  port: 8081
  tomcat:
    max-threads: 10000
    #max-connections: 50000

management:
  security:
    enabled: false
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla:
        http:
          server:
            requests: 1ms, 5ms  