---
server:
  port: 8080

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"   
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true 
      sla:
        http:
          server:
            requests: 1ms, 5ms