global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'reactive-solution-web'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      #- targets: ["192.168.0.164:8080","192.168.0.164:8082"]
      - targets: ["192.168.0.7:8080","192.168.0.7:8082"]
  - job_name: 'sync-solution-web'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ["192.168.0.7:8081"]
